### ISSUE TITLE
errors not recorded in airbrake

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#7]
I've tried using  v.0.7.2 of this plugin and the head of the git repository, but no matter which version I use, the errors do not appear when I login to the airbrake website.

I've uploaded the [sample application](http://festivals.ie:8080/airbrake.zip) I've created to test this plugin, so you can reproduce the problem. If you run this application, then click on the link on the homepage to generate an error, then login to my airbrake account:

https://kaufda.airbrake.io/projects/82838/errors

email: donal.murtagh@kaufda.de
password: playboy,83

you'll see that no errors are recorded

**Comment by coderberry** [comment]
I have checked in an example Grails application at https://github.com/cavneb/ExampleAirbrake.

There are some changes that I made:
- changed depencency to runtime instead of compile in BuildConfig.groovy
- changed the Config.groovy a bit

I am not sure if this will fix your issue, but please do a comparison on it vs. yours and let me know if it works. I was able to submit errors to your Airbrake account, although it nearly times out b/c Airbrake seems super slow as of late.

Eric

**Comment by ghost** [comment]
Thanks very much for your swift response. I made the same changes to BuildConfig.groovy and Config.groovy and it seems to work now, though I don't really understand why, because these changes seem largely inconsequential.

**Comment by jonspalmer** [comment]
Can we close this out?

**Comment by ghost** [comment]
yes
